spring.application.name=guardian-cloud

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/guardian
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Mmesoma12.}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration