spring.application.name=guardian-cloud

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/guardian
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Mmesoma12.}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

guardian.jwt.secret=${GUARDIAN_JWT_SECRET:MhekzOqt2HBAGxZRw/OBFCyfsaFvoxh9WjBp3QDbCzYQgNFG8wS4natPZ4BS/Xu+GLyPtYBml9Nqb3f4Zu0dIw==}
guardian.jwt.expiration-seconds=3600